# Generated by Django 4.2.16 on 2024-12-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bypass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bypassmode',
            name='image',
            field=models.BinaryField(),
        ),
    ]
